services:
  askit_db:
    image: postgres:16
    container_name: askit_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh

  redis:
    image: redis:7-alpine
    container_name: askit_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build: .
    container_name: askit_api
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - askit_db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
