"""initial schema

Revision ID: 472febf91abc
Revises:
Create Date: 2026-07-19 21:53:51.774821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "472febf91abc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=30), nullable=False),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index(op.f("ix_tags_tag_id"), "tags", ["tag_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=50), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=250), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "quizzes",
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.VARCHAR(length=300), nullable=True),
        sa.Column("default_time_per_question", sa.Integer(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("private", "public", name="quizvisibility", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "published", name="quizstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("quiz_id"),
    )
    op.create_index(op.f("ix_quizzes_quiz_id"), "quizzes", ["quiz_id"], unique=False)
    op.create_table(
        "game_sessions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("room_code", sa.VARCHAR(length=6), nullable=False),
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("randomize_questions", sa.Boolean(), nullable=False),
        sa.Column("randomize_answers", sa.Boolean(), nullable=False),
        sa.Column("show_immediate_feedback", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "starting",
                "question",
                "revealing",
                "finished",
                name="gamesessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.quiz_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_game_sessions_room_code"), "game_sessions", ["room_code"], unique=True
    )
    op.create_index(
        op.f("ix_game_sessions_session_id"),
        "game_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "quiz_favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.quiz_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "quiz_id"),
    )
    op.create_table(
        "quiz_questions",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.VARCHAR(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("time_limit", sa.Integer(), nullable=False),
        sa.Column("allow_multiple_answers", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.quiz_id"],
        ),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(
        op.f("ix_quiz_questions_question_id"),
        "quiz_questions",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_questions_quiz_id"), "quiz_questions", ["quiz_id"], unique=False
    )
    op.create_table(
        "quiz_tags",
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.quiz_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.tag_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("quiz_id", "tag_id"),
    )
    op.create_table(
        "game_players",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("nickname", sa.VARCHAR(length=30), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("is_connected", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.session_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_index(
        op.f("ix_game_players_player_id"), "game_players", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_players_session_id"), "game_players", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_players_user_id"), "game_players", ["user_id"], unique=False
    )
    op.create_table(
        "quiz_answers",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.VARCHAR(length=255), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["quiz_questions.question_id"], name="fk_answer_question"
        ),
        sa.PrimaryKeyConstraint("answer_id"),
    )
    op.create_index(
        op.f("ix_quiz_answers_answer_id"), "quiz_answers", ["answer_id"], unique=False
    )
    op.create_table(
        "game_player_answers",
        sa.Column("answer_record_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("selected_answer_ids", sa.VARCHAR(length=1000), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("time_taken_ms", sa.Integer(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["game_players.player_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["quiz_questions.question_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("answer_record_id"),
        sa.UniqueConstraint(
            "player_id", "question_id", name="uq_player_question_answer"
        ),
    )
    op.create_index(
        op.f("ix_game_player_answers_answer_record_id"),
        "game_player_answers",
        ["answer_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_player_answers_player_id"),
        "game_player_answers",
        ["player_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_game_player_answers_player_id"), table_name="game_player_answers"
    )
    op.drop_index(
        op.f("ix_game_player_answers_answer_record_id"),
        table_name="game_player_answers",
    )
    op.drop_table("game_player_answers")
    op.drop_index(op.f("ix_quiz_answers_answer_id"), table_name="quiz_answers")
    op.drop_table("quiz_answers")
    op.drop_index(op.f("ix_game_players_user_id"), table_name="game_players")
    op.drop_index(op.f("ix_game_players_session_id"), table_name="game_players")
    op.drop_index(op.f("ix_game_players_player_id"), table_name="game_players")
    op.drop_table("game_players")
    op.drop_table("quiz_tags")
    op.drop_index(op.f("ix_quiz_questions_quiz_id"), table_name="quiz_questions")
    op.drop_index(op.f("ix_quiz_questions_question_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_table("quiz_favorites")
    op.drop_index(op.f("ix_game_sessions_session_id"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_room_code"), table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_index(op.f("ix_quizzes_quiz_id"), table_name="quizzes")
    op.drop_table("quizzes")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tags_tag_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
