"""add game tables

Revision ID: 8539fea09fae
Revises:
Create Date: 2026-03-20 10:23:46.947509

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8539fea09fae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
